name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run build release
      #run: cargo build --release --verbose
      run: ls
    - name: install youtube-dl
      run: brew install youtube-dl 
    - name: get-the video format 
      run: youtube-dl -F https://www.youtube.com/watch?v=1vvyyhteIv4
    - name: get-the video format -audio
      run: youtube-dl -f 140 https://www.youtube.com/watch?v=1vvyyhteIv4 -o '%(format_id)s-2021-12-11.m4a'
    - name: get-the video
      #run: youtube-dl https://www.youtube.com/watch?v=1vvyyhteIv4
      run: youtube-dl  https://www.youtube.com/watch?v=lT9eLDMCJ_U&list=PLMHbQxe1e9Mk5kOHrm9v20-umkE2ck_gE -o 'video.mp4'
       
    - name: list-files
      run: ls -al .
    - name: Upload file
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: 140-2021-12-11.m4a
        path: 140-2021-12-11.m4a
        #warn: Output a warning but do not fail the action
    - name: Upload a Build Artifact udp-server
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: video.mp4
        path: video.mp4
        warn: Output a warning but do not fail the action
